### PR TITLE
updated the requirements

### PR DESCRIPTION
**Pull request by ndeutschmann**
@NGoetz Could you please also try to `pip install -r requirements.txt` in a clean venv?

### CODE REVIEW

**Comment by NGoetz** [comment]
`ERROR: Could not find a version that satisfies the requirement torch==1.6.0
ERROR: No matching distribution found for torch==1.6.0`

Afaik the package was called pytorch up to and including 1.6.0 . Afterwards it is torch.

**Comment by ndeutschmann** [comment]
As far as I can tell, it does exist in 1.6.0:

https://pypi.org/project/torch/1.6.0

This works with python 3.8.1 on yoshi. Which version are you using?

**Comment by NGoetz** [comment]
I was using 3.9.1 on my laptop. I tried again with 3.8.1 for which it works on my machine too.

**Comment by ndeutschmann** [comment]
Apparently pytorch does not support 3.9 yet. Good to know

**Comment by NGoetz** [comment]
The [Pytorch website](https://pytorch.org/get-started/locally/) says:
`NOTE: Python 3.9 users will need to add '-c=conda-forge' for installation
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch`

**Pull request merged**
